### PR TITLE
Automatically add Dagger Reflect Lint if possible

### PR DESCRIPTION
**Pull request by winterDroid**
In case any Android plugin is applied, we can add the Dagger Reflect lint rules in case reflect version > 0.1.0 is used

### CODE REVIEW

**Comment by winterDroid** [comment]
Lint rules PR can be found [here](https://github.com/JakeWharton/dagger-reflect/pull/137)

**Comment by winterDroid** [comment]
Lint rules PR can be found https://github.com/JakeWharton/dagger-reflect/pull/137

**Comment by rciovati** [comment]
I wonder if it makes more sense to add the Lint check dependency even if dagger reflect is not activated, so that you get the violations also on-local builds (like CI). WDYT?

**Comment by runningcode** [comment]
@winterDroid Looks great!

@rciovati I think it is a good idea to run builds with dagger reflect on CI if it is a feature that one chooses to support. With that said, I would prefer to have the plugin make absolutely no changes if dagger reflect is not enabled.

**Comment by rciovati** [comment]
> With that said, I would prefer to have the plugin make absolutely no changes if dagger reflect is not enabled.

Just to articulate better my thinking: my rationale was that adding an extra lint detector to the dependency it's probably fine in most cases, given that people using the delect plugin sooner rather than later want to use dagger reflect, and way more pragmatic that adding a new dimension on your CI builds (running build, static analysis, tests only for a build with dagger reflect, which is supposed to be a local thing). But I definitely see the point that probably is not the cleanest solution. With that said, one can always add the dependency manually to their build script 👍

**Comment by winterDroid** [comment]
What about an extra option in the extension to always add the Lint dependency?

**Comment by runningcode** [comment]
I like that idea of having an option. 👍

**Pull request merged**
